#!/usr/bin/env bash
# Generated by matugen for Fastfetch. Do not edit this generated file directly.
set -euo pipefail

ansi_fg() {
  local hex="$1"
  hex="${hex#\#}"
  printf '\033[38;2;%d;%d;%dm' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

reset=$'\033[0m'

c1="$(ansi_fg '#ff729a')"
c2="$(ansi_fg '#ff729a')"
c3="$(ansi_fg '#ff9fba')"
c4="$(ansi_fg '#ff9fba')"
c5="$(ansi_fg '#fff872')"
c6="$(ansi_fg '#fff872')"
c7="$(ansi_fg '#fffaa5')"
c8="$(ansi_fg '#fffaa5')"
c9="$(ansi_fg '#8cb3f2')"
c10="$(ansi_fg '#8cb3f2')"
c11="$(ansi_fg '#b3d0ff')"
c12="$(ansi_fg '#b3d0ff')"
c13="$(ansi_fg '#2a4776')"
c14="$(ansi_fg '#2a4776')"
c15="$(ansi_fg '#c0d8ff')"
c16="$(ansi_fg '#c0d8ff')"
c17="$(ansi_fg '#f8fbff')"
c18="$(ansi_fg '#f8fbff')"
c19="$(ansi_fg '#f8fbff')"

printf '%s%s%s\n' "$c1" '                  -`' "$reset"
printf '%s%s%s\n' "$c2" '                 .o+`' "$reset"
printf '%s%s%s\n' "$c3" '                `ooo/' "$reset"
printf '%s%s%s\n' "$c4" '               `+oooo:' "$reset"
printf '%s%s%s\n' "$c5" '              `+oooooo:' "$reset"
printf '%s%s%s\n' "$c6" '              -+oooooo+:' "$reset"
printf '%s%s%s\n' "$c7" '            `/:-:++oooo+:' "$reset"
printf '%s%s%s\n' "$c8" '           `/++++/+++++++:' "$reset"
printf '%s%s%s\n' "$c9" '          `/++++++++++++++:' "$reset"
printf '%s%s%s\n' "$c10" '         `/+++ooooooooooooo/`' "$reset"
printf '%s%s%s\n' "$c11" '        ./ooosssso++osssssso+`' "$reset"
printf '%s%s%s\n' "$c12" '       .oossssso-````/ossssss+`' "$reset"
printf '%s%s%s\n' "$c13" '      -osssssso.      :ssssssso.' "$reset"
printf '%s%s%s\n' "$c14" '     :osssssss/        osssso+++.' "$reset"
printf '%s%s%s\n' "$c15" '    /ossssssss/        +ssssooo/-' "$reset"
printf '%s%s%s\n' "$c16" '  `/ossssso+/:-        -:/+osssso+-' "$reset"
printf '%s%s%s\n' "$c17" ' `+sso+:-`                 `.-/+oso:' "$reset"
printf '%s%s%s\n' "$c18" '`++:.                           `-/+/' "$reset"
printf '%s%s%s\n' "$c19" '.`                                 `/' "$reset"
